### ISSUE TITLE
Split package into small reusable parts

### ISSUE THREAD

**Issue by juliohm** [rmcaixeta/LocalAnisotropies.jl#34]
Hi @rmcaixeta , nice to see the effort around models of local anisotropy. I see that there is a lot of code duplication here where you copied solvers from GeoStats.jl and modified them to achieve what you wanted quickly. As we discussed over Zulip, the best way to maximize the impact is to split the package into small components that can be moved to GeoStatsBase.jl or Meshes.jl for greater reuse across the framework. After all, local anisotropy should be an option in the existing Kriging and simulation solvers, not completely separate solvers.

I am concerned that if we don't tackle this issue now we will just lose the opportunity to have a cohesive treatment of local anisotropy. The effort will be disconnected from the rest of the framework, will get outdated, and that is not a great outcome.

**Comment by rmcaixeta** [comment]
Thanks for registering that, @juliohm
This package was a lab for me to learn julia and more about local anisotropies implementation. The framework will get evolved with time, I'll keep it updated with GeoStats framework until that. I believe that after refactoring kriging for block estimation and cokriging, things will get simplified here too.

I understand that there are two parts to deal: kriging and rotation conventions.

For the first, I think one day it might be enough to pass just a LocalGeoData in the EstimationProblem; or a custom variogram object for kriging (with LocalAnisotropy embedded) and the rest will be natural. I'm not totally sure right now because it has been some time since I coded kriging part, but if variogram function for kriging matrices are built with a variogram function like `γ(GeoData1, GeoData2, ind1, ind2)` instead `γ(point1, point2)`, it'd be possible to remove a lot a kriging code here.

For the second, I belive that ideal solution would be an extra package that deals with rotation conventions. Where anyone could add its own rotation convention rules and output rotation matrix, quaternions, reverse rotation matrix etc. But that might be a little bit challenging too, there are multiple ways of naming and structure conventions, as it is here or in Meshes might not be enough yet.
